export const FETCH_AMOE_START = 'FETCH_AMOE_START';
export const FETCH_AMOE_FAIL = 'FETCH_AMOE_FAIL';
export const FETCH_AMOE_SUCCESS = 'FETCH_AMOE_SUCCESS';
export const RESET_AMOE_DATA = 'RESET_AMOE_DATA';

export const EDIT_AMOE_START = 'EDIT_AMOE_START';
export const EDIT_AMOE_FAIL = 'EDIT_AMOE_FAIL';
export const EDIT_AMOE_SUCCESS = 'EDIT_AMOE_SUCCESS';

export const AMOE_STATUS_START = 'AMOE_STATUS_START';
export const AMOE_STATUS_FAIL = 'AMOE_STATUS_FAIL';
export const AMOE_STATUS_SUCCESS = 'AMOE_STATUS_SUCCESS';
