// Spin-Wheel Action Types
export const GET_SPIN_WHEEL_DATA = 'GET_SPIN_WHEEL_DATA';
export const GET_SPIN_WHEEL_DATA_SUCCESS = 'GET_SPIN_WHEEL_DATA_SUCCESS';
export const GET_SPIN_WHEEL_DATA_FAIL = 'GET_SPIN_WHEEL_DATA_FAIL';

export const UPDATE_SPIN_WHEEL_DATA = 'UPDATE_SPIN_WHEEL_DATA';
export const UPDATE_SPIN_WHEEL_DATA_SUCCESS = 'UPDATE_SPIN_WHEEL_DATA_SUCCESS';
export const UPDATE_SPIN_WHEEL_DATA_FAIL = 'UPDATE_SPIN_WHEEL_DATA_FAIL';
