export const SOCKET_NAMESPACES = {
  WALLET: '/wallet',
  WINNER: '/live-winners',
  LEADER_BOARD: '/leader-board',
  ADMIN_NOTIFICATIONS: '/admin_notification'
}

export const SOCKET_ROOMS = {
  USER_WALLET: 'USER_WALLET',
  LIVE_WINNERS: 'LIVE_WINNERS',
  KYC_STATUS: 'KYC_STATUS',
  LEADER_BOARD: 'LEADER_BOARD',
  ADMIN_NOTIFICATION: 'ADMIN_NOTIFICATION'
}

export const SOCKET_EMITTERS = {
  USER_WALLET_BALANCE: 'USER_WALLET_BALANCE',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  LIVE_GAME_WINNERS: 'LIVE_GAME_WINNERS',
  KYC_STATUS: 'KYC_STATUS_UPDATE',
  LEADER_BOARD_UPDATE: 'LEADER_BOARD_UPDATE',
  DUPLICATE_LOGIN: 'DUPLICATE_LOGIN',
  PAYMENT_STATUS: 'PAYMENT_STATUS'
}
