import config from '../../configs/app.config'

export const SUCCESS_MSG = {
  CREATE_SUCCESS: 'Record created successfully',
  GET_SUCCESS: 'Record get successfully',
  DELETE_SUCCESS: 'Record deleted successfully',
  UPDATE_SUCCESS: 'Record updated successfully',
  LOGIN_SUCCESS: 'User logged in Successfully!',
  STATUS_UPDATED: 'Status has been updated successfully',
  ADD_FAVORITE: 'Game added to favorites successfully',
  REMOVE_FAVORITE: 'Game removed from favorites successfully',
  UPLOAD_SUCCESS: 'Profile image uploaded successfully',
  REMOVE_SUCCESS: 'Profile image removed successfully',
  VERIFICATION_EMAIL: 'Verification email is valid for ' + config.get('jwt.emailTokenExpiry'),
  RESET_PASSWORD_EMAIL: 'Reset password email is valid for ' + config.get('jwt.resetPasswordExpiry'),
  PASSWORD_RESET: 'Password updated',
  KYC_VERIFIED: 'KYC is already verified on some other portal',
  AVAIL_BONUS: 'Bonus Availed successfully.',
  ALREADY_AVAIL_BONUS: 'Bonus already Availed.',
  NOT_FOUND_BONUS: 'Bonus not found.',
  CANCEL_SUCCESS: 'Bonus cancelled successfully',
  EMAIL_SENT: 'Email sent successfully',
  EMAIL_OTP: 'Email OTP Verify successfully',
  TRANSACTION_SUCCESS: 'Transaction successful',
  RESEND_MAIL_SUCCESS: 'The verification code has been resent.',
  RESEND_PHONE_SUCCESS: 'The code has been sent again to your phone number:+',
  OTP_SENT: 'OTP sent successfully',
  OTP_VERIFY: 'OTP verified successfully',
  PHONE_VERIFY: 'Phone verified successfully!',
  FIRST_PURCHASE_BONUS_CREATED: 'first purchase bonus created successfully!',
  DEPOSIT_SUCCESS: 'Amount added successfully',
  WITHDRAW_SUCCESS: 'Amount deducted successfully',
  GENERATE_2FA_SUCCESS: '2FA otp generated successfully',
  VERIFY_2FA_SUCCESS: '2FA otp verified successfully',
  AUTH_DISABLE: '2FA updated successfully',
  WELCOME_BONUS_DECLINED: 'Welcome bonus declined',
  DAILY_BONUS_DECLINED: 'Daily bonus declined'
}
