export const GET_STATS_START = 'GET_STATS_START';
export const GET_STATS_SUCCESS = 'GET_STATS_SUCCESS';
export const GET_STATS_FAIL = 'GET_STATS_FAIL';

// Player info
export const PLAYER_INFO = 'PLAYER_INFO';
export const PLAYER_INFO_SUCCESS = 'PLAYER_INFO_SUCCESS';
export const PLAYER_INFO_FAIL = 'PLAYER_INFO_FAIL';

// Get Demographic view
export const GET_DEMOGRAPHIC_START = 'GET_DEMOGRAPHIC_START';
export const GET_DEMOGRAPHIC_SUCCESS = 'GET_DEMOGRAPHIC_SUCCESS';
export const GET_DEMOGRAPHIC_FAIL = 'GET_DEMOGRAPHIC_FAIL';
// Get KPI REPORT view
export const GET_KPI_REPORT_START = 'GET_KPI_REPORT_START';
export const GET_KPI_REPORT_SUCCESS = 'GET_KPI_REPORT_SUCCESS';
export const GET_KPI_REPORT_FAIL = 'GET_KPI_REPORT_FAIL';

export const RESET_DASHBOARD_STATE = 'RESET_DASHBOARD_STATE';

export const GET_GAME_REPORT_START = 'GET_GAME_REPORT_START';
export const GET_GAME_REPORT_SUCCESS = 'GET_GAME_REPORT_SUCCESS';
export const GET_GAME_REPORT_FAIL = 'GET_GAME_REPORT_FAIL';

export const GET_KPI_SUMMARY_START = 'GET_KPI_SUMMARY_START';
export const GET_KPI_SUMMARY_SUCCESS = 'GET_KPI_SUMMARY_SUCCESS';
export const GET_KPI_SUMMARY_FAIL = 'GET_KPI_SUMMARY_FAIL';

export const GET_TOP_PLAYERS_START = 'GET_TOP_PLAYERS_START';
export const GET_TOP_PLAYERS_SUCCESS = 'GET_TOP_PLAYERS_SUCCESS';
export const GET_TOP_PLAYERS_FAIL = 'GET_TOP_PLAYERS_FAIL';

export const GET_GAME_PLAYER_COUNT_START = 'GET_GAME_PLAYER_COUNT_START';
export const GET_GAME_PLAYER_COUNT_SUCCESS = 'GET_GAME_PLAYER_COUNT_SUCCESS';
export const GET_GAME_PLAYER_COUNT_FAIL = 'GET_GAME_PLAYER_COUNT_FAIL';

export const GET_STATISTICS_SUMMARY_V2_START =
	'GET_STATISTICS_SUMMARY_V2_START';
export const GET_STATISTICS_SUMMARY_V2_SUCCESS =
	'GET_STATISTICS_SUMMARY_V2_SUCCESS';
export const GET_STATISTICS_SUMMARY_V2_FAIL = 'GET_STATISTICS_SUMMARY_V2_FAIL';

export const GET_ACTIVE_USERS_START = 'GET_ACTIVE_USERS_START';
export const GET_ACTIVE_USERS_SUCCESS = 'GET_ACTIVE_USERS_SUCCESS';
export const GET_ACTIVE_USERS_FAIL = 'GET_ACTIVE_USERS_FAIL';

export const GET_BONUS_REPORT_START = 'GET_BONUS_REPORT_START';
export const GET_BONUS_REPORT_SUCCESS = 'GET_BONUS_REPORT_SUCCESS';
export const GET_BONUS_REPORT_FAIL = 'GET_BONUS_REPORT_FAIL';