export const CREATE_TESTIMONIAL_START = 'CREATE_TESTIMONIAL_START';
export const CREATE_TESTIMONIAL_SUCCESS = 'CREATE_TESTIMONIAL_SUCCESS';
export const CREATE_TESTIMONIAL_FAIL = 'CREATE_TESTIMONIAL_FAIL';

export const GET_ALL_TESTIMONIALS = 'GET_ALL_TESTIMONIALS';
export const GET_ALL_TESTIMONIALS_SUCCESS = 'GET_ALL_TESTIMONIALS_SUCCESS';
export const GET_ALL_TESTIMONIALS_FAIL = 'GET_ALL_TESTIMONIALS_FAIL';
export const RESET_ALL_TESTIMONIALS = 'RESET_ALL_TESTIMONIALS';

export const GET_TESTIMONIAL_BY_ID_START = 'GET_TESTIMONIAL_BY_ID_START';
export const GET_TESTIMONIAL_BY_ID_SUCCESS = 'GET_TESTIMONIAL_BY_ID_SUCCESS';
export const GET_TESTIMONIAL_BY_ID_FAIL = 'GET_TESTIMONIAL_BY_ID_FAIL';
export const RESET_TESTIMONIAL_BY_ID = 'RESET_TESTIMONIAL_BY_ID';

export const UPDATE_TESTIMONIAL_STATUS = 'UPDATE_TESTIMONIAL_STATUS';
export const UPDATE_TESTIMONIAL_STATUS_SUCCESS = 'UPDATE_TESTIMONIAL_STATUS_SUCCESS';
export const UPDATE_TESTIMONIAL_STATUS_FAIL = 'UPDATE_TESTIMONIAL_STATUS_FAIL';


export const UPDATE_TESTIMONIAL_START = 'UPDATE_TESTIMONIAL_START';
export const UPDATE_TESTIMONIAL_SUCCESS = 'UPDATE_TESTIMONIAL_SUCCESS';
export const UPDATE_TESTIMONIAL_FAIL = 'UPDATE_TESTIMONIAL_FAIL';

export const DELETE_TESTIMONIAL = 'DELETE_TESTIMONIAL';
export const DELETE_TESTIMONIAL_SUCCESS = 'DELETE_TESTIMONIAL_SUCCESS';
export const DELETE_TESTIMONIAL_FAIL = 'DELETE_TESTIMONIAL_FAIL';

export const GET_TESTIMONIAL_CATEGORIES = 'GET_TESTIMONIAL_CATEGORIES';
export const GET_TESTIMONIAL_CATEGORIES_SUCCESS = 'GET_TESTIMONIAL_CATEGORIES_SUCCESS';
export const GET_TESTIMONIAL_CATEGORIES_FAIL = 'GET_TESTIMONIAL_CATEGORIES_FAIL';

export const SET_TESTIMONIALS = 'SET_TESTIMONIALS';
export const SET_LOADING = 'SET_LOADING';