// Read (Fetch)

export const FETCH_SEGMENTATION = 'FETCH_SEGMENTATION';
export const FETCH_SEGMENTATION_FAIL = 'FETCH_SEGMENTATION_FAIL';
export const FETCH_SEGMENTATION_SUCCESS = 'FETCH_SEGMENTATION_SUCCESS';

// Create
export const CREATE_SEGMENTATION_START = 'CREATE_SEGMENTATION_START';
export const CREATE_SEGMENTATION_SUCCESS = 'CREATE_SEGMENTATION_SUCCESS';
export const CREATE_SEGMENTATION_FAIL = 'CREATE_SEGMENTATION_FAIL';

// Update
export const UPDATE_SEGMENTATION_START = 'UPDATE_SEGMENTATION_START';
export const UPDATE_SEGMENTATION_SUCCESS = 'UPDATE_SEGMENTATION_SUCCESS';
export const UPDATE_SEGMENTATION_FAIL = 'UPDATE_SEGMENTATION_FAIL';

// Delete
export const DELETE_SEGMENTATION_START = 'DELETE_SEGMENTATION_START';
export const DELETE_SEGMENTATION_SUCCESS = 'DELETE_SEGMENTATION_SUCCESS';
export const DELETE_SEGMENTATION_FAIL = 'DELETE_SEGMENTATION_FAIL';

// Fetch Segmentation Constants
export const FETCH_SEGMENTATION_CONSTANTS = 'FETCH_SEGMENTATION_CONSTANTS';
export const FETCH_SEGMENTATION_CONSTANTS_SUCCESS =
	'FETCH_SEGMENTATION_CONSTANTS_SUCCESS';
export const FETCH_SEGMENTATION_CONSTANTS_FAIL =
	'FETCH_SEGMENTATION_CONSTANTS_FAIL';

export const FETCH_SEGMENTATION_DETAILS = 'FETCH_SEGMENTATION_DETAILS';
export const FETCH_SEGMENTATION_DETAILS_SUCCESS =
	'FETCH_SEGMENTATION_DETAILS_SUCCESS';
export const FETCH_SEGMENTATION_DETAILS_FAIL =
	'FETCH_SEGMENTATION_DETAILS_FAIL';
export const RESET_SEGMENTATION_DETAILS = 'RESET_SEGMENTATION_DETAILS';
