/* eslint-disable no-console */
import { isEmpty } from 'lodash';
import { modules } from './permissions';

const sideBarElements = [
	{
		id: 101,
		isSeparator: true,
		title: ' ',
	},
	{
		id: 103,
		isSeparator: true,
		title: ' ',
	},
	{
		id: 1,
		link: '/dashboard',
		label: 'Dashboard',
		searchString: 'default dashboard home',
		iconName: 'bx bx-home-circle',
		linkClass: '',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
	},
	{
		id: 4,
		link: '/players',
		label: 'Players',
		searchString: 'all players',
		iconName: 'bx bx-group',
		linkClass: '',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		module: modules.player,
	},
	{
		id: 19,
		link: '/#',
		label: 'Reports',
		searchString: 'reports',
		iconName: 'bx bxs-report',
		linkClass: 'has-arrow',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		groupedModules: [
			modules.reportLedger,
			modules.reportTransaction,
			modules.reportCasinoTransaction,
			modules.gameReport,
			modules.reportPlayerPerformance,
		],
		subMenu: [
			{
				id: 116,
				link: '/ledgers',
				label: 'Ledgers',
				searchString: 'Ledgers',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.reportLedger,
			},
			{
				id: 20,
				link: '/transaction',
				label: 'Transactions',
				searchString: 'transaction',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.reportTransaction,
			},
			{
				id: 21,
				link: '/casino-transactions',
				label: 'Casino Transactions',
				searchString: 'casino transactions',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.reportCasinoTransaction,
			},
			{
				id: 23,
				link: '/game-report',
				label: 'Game Reports',
				searchString: 'game report transactions',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.gameReport,
			},
			{
				id: 107,
				link: '/player-performance',
				label: 'Player Performance',
				searchString: 'player performance',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.reportPlayerPerformance,
			},
			// {
			// 	id: 112,
			// 	link: '/redeem-requests',
			// 	label: 'Redeem Requests',
			// 	searchString: 'Redeem Requests',
			// 	iconName: '',
			// 	linkClass: '',
			// 	anchorClass: '',
			// 	spanClass: '',
			// 	liTagClass: '',
			// 	ulTagClass: '',
			// 	module: modules.redeem,
			// },
			// {
			// 	id: 30,
			// 	link: '/withdraw-request',
			// 	label: 'Withdraw Request',
			// 	searchString: 'withdraw requests',
			// 	iconName: '',
			// 	linkClass: '',
			// 	anchorClass: '',
			// 	spanClass: '',
			// 	liTagClass: '',
			// 	ulTagClass: '',
			// 	module: modules.report,
			// },
		],
	},
	{
		id: 115,
		isSeparator: true,
		title: '',
	},
	{
		id: 6,
		link: '/#',
		label: 'Site Configuration',
		searchString: 'site configuration',
		iconName: 'bx bx-cog',
		linkClass: 'has-arrow',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		groupedModules: [modules.applicationSetting, modules.coin, modules.state],
		subMenu: [
			{
				id: 7,
				link: '/coins',
				label: 'Coins',
				searchString: 'Coins',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				// module: modules.coin,
			},
			{
				id: 8,
				link: '/states',
				label: 'States',
				searchString: 'states',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.state,
			},
			// {
			// 	id: 9,
			// 	link: '/languages',
			// 	label: 'Languages',
			// 	searchString: 'languages',
			// 	iconName: '',
			// 	linkClass: '',
			// 	anchorClass: '',
			// 	spanClass: '',
			// 	liTagClass: '',
			// 	ulTagClass: '',
			// 	module: modules.language,
			// },
			{
				id: 10,
				link: '/application-settings',
				label: 'Application Settings',
				searchString: 'application settings',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.applicationSetting,
			},
			// {
			// 	id: 31,
			// 	link: '/review-management',
			// 	label: 'Review Management',
			// 	searchString: 'review management',
			// 	iconName: '',
			// 	linkClass: '',
			// 	anchorClass: '',
			// 	spanClass: '',
			// 	liTagClass: '',
			// 	ulTagClass: '',
			// 	module: modules.review,
			// },
			// {
			// 	id: 9,
			// 	link: '/languages-management',
			// 	label: 'Languages Management',
			// 	searchString: 'languages management',
			// 	iconName: '',
			// 	linkClass: '',
			// 	anchorClass: '',
			// 	spanClass: '',
			// 	liTagClass: '',
			// 	ulTagClass: '',
			// 	module: modules.language,
			// },
			// {
			// 	id: 10,
			// 	link: '/form-fields',
			// 	label: 'Registration Fields',
			// 	searchString: 'registration fields',
			// 	iconName: '',
			// 	linkClass: '',
			// 	anchorClass: '',
			// 	spanClass: '',
			// 	liTagClass: '',
			// 	ulTagClass: '',
			// 	module: modules.RegistrationField,
			// },
		],
	},

	{
		id: 12,
		link: '/#',
		label: 'Content Management',
		searchString: 'content management',
		iconName: 'bx bx-customize',
		linkClass: 'has-arrow',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		groupedModules: [
			modules.page,
			// modules.notification,
			// modules.segmentation,
			modules.gallery,
			modules.banner,
			modules.seoPage,
			modules.emailTemplate,
			modules.testimonial,
		],
		subMenu: [
			{
				id: 12,
				link: '/cms',
				label: 'CMS',
				searchString: 'cms',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.page,
			},
			// {
			// 	id: 37,
			// 	link: '/notifications',
			// 	label: 'Notifications',
			// 	searchString: 'notification',
			// 	iconName: '',
			// 	linkClass: '',
			// 	anchorClass: '',
			// 	spanClass: '',
			// 	liTagClass: '',
			// 	ulTagClass: '',
			// 	module: modules.notification,
			// },
			// {
			// 	id: 112,
			// 	link: '/dispute-resolution',
			// 	label: 'Dispute Resolution',
			// 	searchString: 'dispute resolution',
			// 	iconName: '',
			// 	linkClass: '',
			// 	anchorClass: '',
			// 	spanClass: '',
			// 	liTagClass: '',
			// 	ulTagClass: '',
			// 	module: modules.page,
			// },
			// {
			// 	id: 124,
			// 	link: '/seo-slugs',
			// 	label: 'Seo Slugs',
			// 	searchString: 'seo slugs',
			// 	iconName: 'fas fa-link',
			// 	linkClass: '',
			// 	anchorClass: '',
			// 	spanClass: '',
			// 	liTagClass: '',
			// 	ulTagClass: '',
			// 	groupedModules: [modules.seoPage],
			// },
			{
				id: 14,
				link: '/image-gallery',
				label: 'Image Gallery',
				searchString: 'image gallery',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.gallery,
			},
			// {
			// 	id: 14,
			// 	link: '/image-gallery',
			// 	label: 'Image Gallery',
			// 	searchString: 'image gallery',
			// 	iconName: '',
			// 	linkClass: '',
			// 	anchorClass: '',
			// 	spanClass: '',
			// 	liTagClass: '',
			// 	ulTagClass: '',
			// 	module: modules.gallery,
			// },
			{
				id: 15,
				link: '/banner-management',
				label: 'Banner Management',
				searchString: 'banner management home banner',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.banner,
			},
			{
				id: 42,
				link: '/email-templates',
				label: 'Email Templates',
				searchString: 'email-templates',
				iconName: 'bx bx-user-plus',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.emailTemplate,
			},
			{
				id: 127,
				link: '/testimonials',
				label: 'Testimonials',
				searchString: 'testimonials',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.testimonial,
			},
		],
	},
	{
		id: 112,
		link: '/segmentation',
		label: 'Segmentation',
		searchString: 'Segmentation',
		iconName: 'bx bx-group',
		linkClass: '',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		module: modules.segmentation,
	},
	{
		id: 123,
		link: '/advance-filter',
		label: 'Advance Filter',
		searchString: 'tournaments',
		iconName: 'bx bx-filter-alt',
		linkClass: '',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		module: modules.segmentation,
	},
	// {
	// 	id: 125,
	// 	link: '/admin-activity',
	// 	label: 'Admin Activity',
	// 	searchString: 'admin-activity',
	// 	iconName: 'fa fa-book',
	// 	linkClass: '',
	// 	anchorClass: '',
	// 	spanClass: '',
	// 	liTagClass: '',
	// 	ulTagClass: '',
	// 	module: modules.segmentation,
	// },
	// {
	// 	id: 108,
	// 	link: '/tournaments',
	// 	label: 'Tournaments',
	// 	searchString: 'tournaments',
	// 	iconName: 'bx bxs-trophy',
	// 	linkClass: '',
	// 	anchorClass: '',
	// 	spanClass: '',
	// 	liTagClass: '',
	// 	ulTagClass: '',
	// 	module: modules.tournamentManagement,
	// },
	// {
	// 	id: 109,
	// 	link: '/payment',
	// 	label: 'Payment Management',
	// 	searchString: 'payment',
	// 	iconName: 'bx bx-credit-card',
	// 	linkClass: '',
	// 	anchorClass: '',
	// 	spanClass: '',
	// 	liTagClass: '',
	// 	ulTagClass: '',
	// 	// module: modules.paymentManagement,
	// },
	{
		id: 114,
		link: '/packages',
		label: 'Packages',
		searchString: 'packages',
		iconName: 'mdi mdi-gift-outline',
		linkClass: '',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		module: modules.package,
	},
	{
		id: 121,
		link: '/vip',
		label: 'VIP',
		searchString: 'vip',
		iconName: 'bx bx-crown',
		linkClass: '',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		module: modules.vip,
	},
	{
		id: 122,
		isSeparator: true,
		title: 'Bonuses',
		groupedModules: [
			modules.bonus,
			modules.vip,
			modules.referral,
			modules.spinWheelConfiguration,
		],
	},
	{
		id: 16,
		link: '/bonus',
		label: 'Bonus Management',
		searchString: 'bonus management',
		iconName: 'bx bx-money',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		module: modules.bonus,
	},
	{
		id: 111,
		link: '/referral',
		label: 'Referral Management',
		searchString: 'referral management',
		iconName: 'mdi mdi-handshake-outline',
		linkClass: '',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		module: modules.referral,
	},
	{
		id: 117,
		link: '/amoe',
		label: 'AMOE',
		searchString: 'amoe',
		iconName: 'mdi mdi-location-enter',
		linkClass: '',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		module: modules.amoe,
	},
	// {
	// 	id: 104,
	// 	isSeparator: true,
	// 	title: 'Statements',
	// 	groupedModules: [modules.report, modules.review],
	// },
	{
		id: 118,
		link: '/spin-wheel',
		label: 'Spin Wheel',
		searchString: 'Spin Wheel',
		iconName: 'mdi mdi-ship-wheel',
		linkClass: '',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		module: modules.spinWheelConfiguration,
	},
	{
		id: 119,
		isSeparator: true,
		title: 'Payments',
		groupedModules: [modules.paymentManagement, modules.redeem],
	},
	{
		id: 109,
		link: '/payment',
		label: 'Payment Management',
		searchString: 'payment',
		iconName: 'bx bx-credit-card',
		linkClass: '',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		module: modules.paymentManagement,
	},
	{
		id: 120,
		link: '/redeem-requests',
		label: 'Redeem Requests',
		searchString: 'redeem requests',
		iconName: 'mdi mdi-account-cash-outline',
		linkClass: '',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		module: modules.redeem,
	},
	{
		id: 102,
		isSeparator: true,
		title: 'Casino',
		groupedModules: [modules.casinoManagement],
	},
	// {
	// 	id: 25,
	// 	link: '/#',
	// 	label: 'Casino Management',
	// 	searchString: 'casino management slot',
	// 	iconName: 'bx bx-list-ul',
	// 	linkClass: 'has-arrow',
	// 	anchorClass: '',
	// 	spanClass: '',
	// 	liTagClass: '',
	// 	ulTagClass: '',
	// 	groupedModules: [modules.casinoManagement],
	// 	subMenu: [

	// 	],
	// },
	{
		id: 26,
		link: '/casino-aggregators',
		label: 'Aggregators',
		searchString: 'casino aggregators',
		iconName: 'mdi mdi-cards-club',
		linkClass: '',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		module: modules.casinoManagement,
	},
	{
		id: 27,
		link: '/casino-providers',
		label: 'Providers',
		searchString: 'casino providers',
		iconName: 'mdi mdi-poker-chip',
		linkClass: '',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		module: modules.casinoManagement,
	},
	{
		id: 30,
		link: '/casino-games',
		label: 'Games',
		searchString: 'casino games',
		iconName: 'mdi mdi-gamepad-variant-outline',
		linkClass: '',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		module: modules.casinoManagement,
	},
	{
		id: 28,
		link: '/categories',
		label: 'Categories',
		searchString: 'casino categories',
		iconName: 'mdi mdi-slot-machine-outline',
		linkClass: '',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		module: modules.casinoManagement,
	},
	{
		id: 105,
		isSeparator: true,
		title: 'Staff Management',
		groupedModules: [modules.admin],
	},
	{
		id: 3,
		link: '/staff',
		label: 'Staff',
		searchString: 'staff admin superadmin listing',
		iconName: 'bx bx-user-plus',
		linkClass: '',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		module: modules.admin,
	},
	// {
	// 	id: 110,
	// 	isSeparator: true,
	// 	title: 'Player verification',
	// 	groupedModules: [modules.kyc],
	// },
	// {
	// 	id: 5,
	// 	link: '/kyc-labels',
	// 	label: 'KYC Labels',
	// 	searchString: 'kyc labels',
	// 	iconName: 'bx bx-list-check',
	// 	linkClass: '',
	// 	anchorClass: '',
	// 	spanClass: '',
	// 	liTagClass: '',
	// 	ulTagClass: '',
	// 	module: modules.kyc,
	// },
	// {
	// 	id: 111,
	// 	isSeparator: true,
	// 	title: 'Chat',
	// 	groupedModules: [modules.paymentManagement],
	// },
	// {
	// 	id: 38,
	// 	link: '/#',
	// 	label: 'Chat Management',
	// 	searchString: 'chat management',
	// 	iconName: 'bx bx-group',
	// 	linkClass: 'has-arrow',
	// 	anchorClass: '',
	// 	spanClass: '',
	// 	liTagClass: '',
	// 	ulTagClass: '',
	// 	groupedModules: [modules.paymentManagement],
	// 	subMenu: [
	// 		{
	// 			id: 40,
	// 			link: '/chat/channels',
	// 			label: 'Channels',
	// 			searchString: 'channels',
	// 			iconName: '',
	// 			linkClass: '',
	// 			anchorClass: '',
	// 			spanClass: '',
	// 			liTagClass: '',
	// 			ulTagClass: '',
	// 			module: modules.paymentManagement,
	// 		},
	// 		// {
	// 		// 	id: 41,
	// 		// 	link: '/chat/chat-rain',
	// 		// 	label: 'Chat Rain',
	// 		// 	searchString: 'chat rain',
	// 		// 	iconName: '',
	// 		// 	linkClass: '',
	// 		// 	anchorClass: '',
	// 		// 	spanClass: '',
	// 		// 	liTagClass: '',
	// 		// 	ulTagClass: '',
	// 		// 	module: modules.paymentManagement,
	// 		// },
	// 	],
	// },
];

// For maintaining single source of truth (SSOT)
const getMegaMenuElement = () => {
	try {
		let id = 1;
		const megaMenu = [];
		let megaEle = {};
		let subMenu = [];

		for (let i = 0; i < sideBarElements?.length; i += 1) {
			const tab = sideBarElements[i];
			if (tab.isSeparator) {
				if (!isEmpty(subMenu)) {
					megaEle.subMenu = subMenu;
					megaMenu.push(megaEle);
					subMenu = [];
				}
				megaEle = {
					id,
					link: '#!',
					label: tab.title,
					...tab,
				};
				id += 1;
			} else {
				subMenu.push(tab);
				if (!isEmpty(tab.subMenu)) {
					subMenu.push(...tab.subMenu);
				}
			}
		}
		megaEle.subMenu = subMenu;
		megaMenu.push(megaEle);

		const filterMenu = [];

		megaMenu.forEach((menu) => {
			filterMenu.push({
				...menu,
				subMenu: menu.subMenu.filter((ele) => ele.link !== '/#'),
			});
		});

		return filterMenu;
	} catch (er) {
		console.log(er);
		return [];
	}
};

export { sideBarElements, getMegaMenuElement };
