export const FETCH_STATES_START = 'FETCH_STATES_START';
export const FETCH_STATES_FAIL = 'FETCH_STATES_FAIL';
export const FETCH_STATES_SUCCESS = 'FETCH_STATES_SUCCESS';
export const RESET_STATES_DATA = 'RESET_STATES_DATA';

export const UPDATE_STATES_STATUS_START = 'UPDATE_STATES_STATUS_START';
export const UPDATE_STATES_STATUS_FAIL = 'UPDATE_STATES_STATUS_FAIL';
export const UPDATE_STATES_STATUS_SUCCESS = 'UPDATE_STATES_STATUS_SUCCESS';
