export const GET_ALL_SEO_ROUTES_START = 'GET_ALL_SEO_ROUTES_START';
export const GET_ALL_SEO_ROUTES_SUCCESS = 'GET_ALL_SEO_ROUTES_SUCCESS';
export const GET_ALL_SEO_ROUTES_FAIL = 'GET_ALL_SEO_ROUTES_FAIL';

export const GET_SEO_ROUTE_START = 'GET_SEO_ROUTE_START';
export const GET_SEO_ROUTE_SUCCESS = 'GET_SEO_ROUTE_SUCCESS';
export const GET_SEO_ROUTE_FAIL = 'GET_SEO_ROUTE_FAIL';

export const CREATE_SEO_ROUTE_START = 'CREATE_SEO_ROUTE_START';
export const CREATE_SEO_ROUTE_SUCCESS = 'CREATE_SEO_ROUTE_SUCCESS';
export const CREATE_SEO_ROUTE_FAIL = 'CREATE_SEO_ROUTE_FAIL';

export const UPDATE_SEO_ROUTE_START = 'UPDATE_SEO_ROUTE_START';
export const UPDATE_SEO_ROUTE_SUCCESS = 'UPDATE_SEO_ROUTE_SUCCESS';
export const UPDATE_SEO_ROUTE_FAIL = 'UPDATE_SEO_ROUTE_FAIL';

export const DELETE_SEO_ROUTE_START = 'DELETE_SEO_ROUTE_START';
export const DELETE_SEO_ROUTE_SUCCESS = 'DELETE_SEO_ROUTE_SUCCESS';
export const DELETE_SEO_ROUTE_FAIL = 'DELETE_SEO_ROUTE_FAIL';
