export const GET_VIP_TIER_START = 'GET_VIP_TIER_START';
export const GET_VIP_TIER_SUCCESS = 'GET_VIP_TIER_SUCCESS';
export const GET_VIP_TIER_FAIL = 'GET_VIP_TIER_FAIL';

export const EDIT_VIP_TIER_START = 'EDIT_VIP_TIER_START';
export const EDIT_VIP_TIER_SUCCESS = 'EDIT_VIP_TIER_SUCCESS';
export const EDIT_VIP_TIER_FAIL = 'EDIT_VIP_TIER_FAIL';

export const CREATE_VIP_TIER_START = 'CREATE_VIP_TIER_START';
export const CREATE_VIP_TIER_SUCCESS = 'CREATE_VIP_TIER_SUCCESS';
export const CREATE_VIP_TIER_FAIL = 'CREATE_VIP_TIER_FAIL';

export const GET_VIP_TIER_BY_ID_START = 'GET_VIP_TIER_BY_ID_START';
export const GET_VIP_TIER_BY_ID_SUCCESS = 'GET_VIP_TIER_BY_ID_SUCCESS';
export const GET_VIP_TIER_BY_ID_FAIL = 'GET_VIP_TIER_BY_ID_FAIL';
