export const ADD_RESTRICTED_STATES_START = 'ADD_RESTRICTED_STATES_START';
export const ADD_RESTRICTED_STATES_FAIL = 'ADD_RESTRICTED_STATES_FAIL';
export const ADD_RESTRICTED_STATES_SUCCESS = 'ADD_RESTRICTED_STATES_SUCCESS';
