// Read (Fetch)

export const FETCH_ADMIN_ACTIVITY = 'FETCH_ADMIN_ACTIVITY';
export const FETCH_ADMIN_ACTIVITY_FAIL = 'FETCH_ADMIN_ACTIVITY_FAIL';
export const FETCH_ADMIN_ACTIVITY_SUCCESS = 'FETCH_ADMIN_ACTIVITY_SUCCESS';
